<template><div><h1 id="meet-confetti" tabindex="-1"><a class="header-anchor" href="#meet-confetti" aria-hidden="true">#</a> Meet Confetti</h1>
<p>Confetti is a web framework written in Go (Golang). The web framework consists of the most important components to create your application. The goal of Confetti is to give you all the tools you need to write fast, secure and scalable code.</p>
<p>Whether you are new to Go or web frameworks or have years of experience, Confetti is a perfect framework that fits into any web development project.</p>
<h2 id="why-confetti" tabindex="-1"><a class="header-anchor" href="#why-confetti" aria-hidden="true">#</a> Why Confetti?</h2>
<p>Confetti has been influenced by <a href="https://laravel.com" target="_blank" rel="noopener noreferrer">Laravel<ExternalLinkIcon/></a>. That's because Laravel provides the perfect functionalists you need to build an application the right way. Laravel is built with PHP, but some projects need better asynchronous, static typing and more performance. It turned out: Go does very well in these subjects. Besides that, Go shows that it is a language with extremely simple syntax, easy to learn and very easy to deploy.</p>
<blockquote>
<p>Confetti combines the elegance of Laravel and the simplicity of Go.</p>
</blockquote>
<h2 id="feel-at-home" tabindex="-1"><a class="header-anchor" href="#feel-at-home" aria-hidden="true">#</a> Feel at home</h2>
<p>If you feel at home, we have achieved a goal. Here is an example to make you feel at home. If you don't understand the following, don't feel overwhelmed. The documentation will guide you.</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">func</span> <span class="token function">OrderStore</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
	app <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">App</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

	<span class="token comment">// Validate JSON content from the request body</span>
	failures <span class="token operator">:=</span> val<span class="token punctuation">.</span><span class="token function">Validate</span><span class="token punctuation">(</span>app<span class="token punctuation">,</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
		val<span class="token punctuation">.</span><span class="token function">Verify</span><span class="token punctuation">(</span><span class="token string">"orders"</span><span class="token punctuation">,</span> rule<span class="token punctuation">.</span>Min<span class="token punctuation">{</span>Len<span class="token punctuation">:</span> <span class="token number">1</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
		val<span class="token punctuation">.</span><span class="token function">Verify</span><span class="token punctuation">(</span><span class="token string">"orders.*.name"</span><span class="token punctuation">,</span> rule<span class="token punctuation">.</span>Required<span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span> rule<span class="token punctuation">.</span>String<span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
		val<span class="token punctuation">.</span><span class="token function">Verify</span><span class="token punctuation">(</span><span class="token string">"orders.*.street"</span><span class="token punctuation">,</span> rule<span class="token punctuation">.</span>Required<span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span> rule<span class="token punctuation">.</span>String<span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
	<span class="token punctuation">)</span>
	<span class="token keyword">if</span> <span class="token function">len</span><span class="token punctuation">(</span>failures<span class="token punctuation">)</span> <span class="token operator">></span> <span class="token number">0</span> <span class="token punctuation">{</span>
		app<span class="token punctuation">.</span><span class="token function">Log</span><span class="token punctuation">(</span><span class="token string">"slack"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Notice</span><span class="token punctuation">(</span><span class="token string">"%b incorrect orders given"</span><span class="token punctuation">,</span> <span class="token function">len</span><span class="token punctuation">(</span>failures<span class="token punctuation">)</span><span class="token punctuation">)</span>
		<span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Json</span><span class="token punctuation">(</span>failures<span class="token punctuation">)</span>
	<span class="token punctuation">}</span>

	<span class="token comment">// (...)</span>

	<span class="token comment">// Return the response with the saved orders</span>
	<span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Json</span><span class="token punctuation">(</span>orders<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


