export const data = JSON.parse("{\"key\":\"v-a0fbbff8\",\"path\":\"/digging-deeper/commands.html\",\"title\":\"Commands\",\"lang\":\"en-US\",\"frontmatter\":{},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"Introduction\",\"slug\":\"introduction\",\"link\":\"#introduction\",\"children\":[]},{\"level\":2,\"title\":\"Installation\",\"slug\":\"installation\",\"link\":\"#installation\",\"children\":[]},{\"level\":2,\"title\":\"Usage\",\"slug\":\"usage\",\"link\":\"#usage\",\"children\":[]},{\"level\":2,\"title\":\"Baker (REPL)\",\"slug\":\"baker-repl\",\"link\":\"#baker-repl\",\"children\":[{\"level\":3,\"title\":\"Usage\",\"slug\":\"usage-1\",\"link\":\"#usage-1\",\"children\":[]}]},{\"level\":2,\"title\":\"Writing Commands\",\"slug\":\"writing-commands\",\"link\":\"#writing-commands\",\"children\":[{\"level\":3,\"title\":\"Your First Command\",\"slug\":\"your-first-command\",\"link\":\"#your-first-command\",\"children\":[]},{\"level\":3,\"title\":\"Command Structure\",\"slug\":\"command-structure\",\"link\":\"#command-structure\",\"children\":[]}]},{\"level\":2,\"title\":\"Defining Input Expectations\",\"slug\":\"defining-input-expectations\",\"link\":\"#defining-input-expectations\",\"children\":[{\"level\":3,\"title\":\"Flags\",\"slug\":\"flags\",\"link\":\"#flags\",\"children\":[]},{\"level\":3,\"title\":\"Input Descriptions\",\"slug\":\"input-descriptions\",\"link\":\"#input-descriptions\",\"children\":[]},{\"level\":3,\"title\":\"Required Fields\",\"slug\":\"required-fields\",\"link\":\"#required-fields\",\"children\":[]},{\"level\":3,\"title\":\"Custom Types (Getters)\",\"slug\":\"custom-types-getters\",\"link\":\"#custom-types-getters\",\"children\":[]}]},{\"level\":2,\"title\":\"Command I/O\",\"slug\":\"command-i-o\",\"link\":\"#command-i-o\",\"children\":[{\"level\":3,\"title\":\"Retrieving Input\",\"slug\":\"retrieving-input\",\"link\":\"#retrieving-input\",\"children\":[]},{\"level\":3,\"title\":\"Prompting For Input\",\"slug\":\"prompting-for-input\",\"link\":\"#prompting-for-input\",\"children\":[]},{\"level\":3,\"title\":\"Writing Output\",\"slug\":\"writing-output\",\"link\":\"#writing-output\",\"children\":[]}]},{\"level\":2,\"title\":\"Registering Commands\",\"slug\":\"registering-commands\",\"link\":\"#registering-commands\",\"children\":[]},{\"level\":2,\"title\":\"Programmatically Executing Commands\",\"slug\":\"programmatically-executing-commands\",\"link\":\"#programmatically-executing-commands\",\"children\":[]}],\"git\":{\"contributors\":[{\"name\":\"Reindert\",\"email\":\"16726304+reindert-vetter@users.noreply.github.com\",\"commits\":1},{\"name\":\"Reindert Vetter\",\"email\":\"reindert@plugandpay.nl\",\"commits\":1},{\"name\":\"Vaggelis Yfantis\",\"email\":\"vaggelisyfantis@gmail.com\",\"commits\":1}]},\"filePathRelative\":\"digging-deeper/commands.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
