<template><h1 id="requests" tabindex="-1"><a class="header-anchor" href="#requests" aria-hidden="true">#</a> Requests</h1>
<h2 id="accessing-the-request" tabindex="-1"><a class="header-anchor" href="#accessing-the-request" aria-hidden="true">#</a> Accessing The Request</h2>
<p>In the parameter from a controller you get a <code v-pre>inter.Request</code> instance. From the request you can view all information
that has been sent to you. Think for example of cookies, headers, body and query parameters.</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">package</span> controller

<span class="token keyword">import</span> <span class="token punctuation">(</span>
    <span class="token string">"github.com/confetti-framework/contract/inter"</span>
    <span class="token string">"github.com/confetti-framework/routing/outcome"</span>
<span class="token punctuation">)</span>

<span class="token keyword">func</span> <span class="token function">UserStore</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
    name <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    <span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Html</span><span class="token punctuation">(</span><span class="token string">"Username:"</span> <span class="token operator">+</span> name<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><p>More information about receiving a parameter, see: <RouterLink to="/the-basics/routing.html#route-parameters">Route Parameters</RouterLink></p>
<h3 id="accessing-the-request-via-route-closures" tabindex="-1"><a class="header-anchor" href="#accessing-the-request-via-route-closures" aria-hidden="true">#</a> Accessing The Request Via Route Closures</h3>
<p>You can also receive the <code v-pre>request</code> interface on a route Closure. Confetti inject the incoming request into the Closure
when it is executed:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
    <span class="token comment">//</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h3 id="original-request" tabindex="-1"><a class="header-anchor" href="#original-request" aria-hidden="true">#</a> Original Request</h3>
<p>If you need to use <code v-pre>net.Request</code> for a library, or you want information that is only available in the original Golang
request. Then you can retrieve it by the <code v-pre>Source</code> method:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>request<span class="token punctuation">.</span><span class="token function">Source</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>URL<span class="token punctuation">.</span>Scheme
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="request-path-method" tabindex="-1"><a class="header-anchor" href="#request-path-method" aria-hidden="true">#</a> Request Path &amp; Method</h3>
<p>The <code v-pre>inter.Request</code> instance provides a variety of methods for examining the HTTP request for your application. We will
discuss a few of the most important methods below.</p>
<h4 id="retrieving-the-request-path" tabindex="-1"><a class="header-anchor" href="#retrieving-the-request-path" aria-hidden="true">#</a> Retrieving The Request Path</h4>
<p>The <code v-pre>Path</code> method returns the request's path information. So, if the incoming request is targeted
at <code v-pre>http://domain.com/foo/bar</code>, the <code v-pre>Path</code> method will return <code v-pre>foo/bar</code>:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>path <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Path</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h4 id="retrieving-the-request-url" tabindex="-1"><a class="header-anchor" href="#retrieving-the-request-url" aria-hidden="true">#</a> Retrieving The Request URL</h4>
<p>To retrieve the full URL for the incoming request you may use the <code v-pre>Url</code> or <code v-pre>FullUrl</code> methods. The <code v-pre>Url</code> method will
return the URL without the query string, while the <code v-pre>FullUrl</code> method includes the query string:</p>
<h5 id="without-query-string" tabindex="-1"><a class="header-anchor" href="#without-query-string" aria-hidden="true">#</a> Without Query String:</h5>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>url <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Url</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h5 id="with-query-string" tabindex="-1"><a class="header-anchor" href="#with-query-string" aria-hidden="true">#</a> With Query String:</h5>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>url <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">FullUrl</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h4 id="retrieving-the-request-method" tabindex="-1"><a class="header-anchor" href="#retrieving-the-request-method" aria-hidden="true">#</a> Retrieving The Request Method</h4>
<p>The <code v-pre>Method</code> method will return the HTTP verb for the request:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>method <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Method</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>You may use the <code v-pre>IsMethod</code> helper method to verify that the HTTP verb matches a given string:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">if</span> http_helper<span class="token punctuation">.</span><span class="token function">IsMethod</span><span class="token punctuation">(</span>request<span class="token punctuation">,</span> method<span class="token punctuation">.</span>Post<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">//</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h2 id="retrieving-input-value" tabindex="-1"><a class="header-anchor" href="#retrieving-input-value" aria-hidden="true">#</a> Retrieving Input Value</h2>
<h3 id="retrieving-an-input-value" tabindex="-1"><a class="header-anchor" href="#retrieving-an-input-value" aria-hidden="true">#</a> Retrieving An Input Value</h3>
<p>Using a few simple methods, you may access the user input from your <code v-pre>http.request</code> instance. Depending on the <code v-pre>Content-Type</code> header, the <code v-pre>Content</code> method may be used to retrieve user input:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>name <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>You may pass a default value as the second argument to the <code v-pre>ContentOr</code> method. This value will be returned if the requested input value is not present on the request:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>name <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">ContentOr</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">,</span> <span class="token string">"Sally"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>When working with forms that contain array inputs, use &quot;dot&quot; notation to access the arrays:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>name <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"names.1"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
name<span class="token punctuation">,</span> err <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"names.1"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">StringE</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
names <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"names.*"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Collection</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>You may call the <code v-pre>Content</code> method with an empty string in order to retrieve all of the input values as support.Map:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>requestValues <span class="token operator">=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">""</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Map</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="retrieving-json-input-values" tabindex="-1"><a class="header-anchor" href="#retrieving-json-input-values" aria-hidden="true">#</a> Retrieving JSON Input Values</h3>
<p>When sending JSON requests to your application, you may access the JSON data via the <code v-pre>Body</code> method as long as the <code v-pre>Content-Type</code> header of the request is properly set to <code v-pre>application/json</code>. You may even use &quot;dot&quot; syntax to dig into JSON arrays:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>name <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"data.address.street"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="retrieving-raw-content-data" tabindex="-1"><a class="header-anchor" href="#retrieving-raw-content-data" aria-hidden="true">#</a> Retrieving Raw Content Data</h3>
<p>To receive the data as it was sent, use the <code v-pre>Body</code> method. In that case you will always receive a string</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>rawContent <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Body</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="retrieving-input-from-the-query-string" tabindex="-1"><a class="header-anchor" href="#retrieving-input-from-the-query-string" aria-hidden="true">#</a> Retrieving Input From The Query String</h3>
<p>While the <code v-pre>Content</code> method retrieves values from the request payload, the <code v-pre>Parameter</code> method will retrieve values from the url, and the query string:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>name <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>You may pass a default value as the second argument to the <code v-pre>ParameterOr</code> method. If the requested query string value data is not present, the second argument to this method will be returned:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>name <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">ParameterOr</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">,</span> <span class="token string">"Sally"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>You may call the <code v-pre>Parameter</code> method with an empty string in order to retrieve all the query string values as support.Map:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>parameters <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">""</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Map</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="retrieving-boolean-input-values" tabindex="-1"><a class="header-anchor" href="#retrieving-boolean-input-values" aria-hidden="true">#</a> Retrieving Boolean Input Values</h3>
<p>When dealing with HTML elements like checkboxes, your application may receive &quot;truthy&quot; values that are actually strings. For example, &quot;true&quot; or &quot;on&quot;. For convenience, you may use the <code v-pre>Bool</code> method to retrieve these values as booleans. The <code v-pre>Bool</code> method returns <code v-pre>true</code> for 1, &quot;1&quot;, true, &quot;true&quot;, &quot;on&quot;, and &quot;yes&quot;. All other values will return <code v-pre>false</code>:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>archived <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"archived"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Bool</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="retrieving-a-portion-of-the-input-data" tabindex="-1"><a class="header-anchor" href="#retrieving-a-portion-of-the-input-data" aria-hidden="true">#</a> Retrieving A Portion Of The Input Data</h3>
<p>If you need to retrieve a subset of the input data, you may use the <code v-pre>Only</code> and <code v-pre>Except</code> methods. Both of these methods accept dynamic list of arguments:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"data.user"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Map</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Only</span><span class="token punctuation">(</span><span class="token string">"username"</span><span class="token punctuation">,</span> <span class="token string">"password"</span><span class="token punctuation">)</span>
request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"data.user"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Map</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Except</span><span class="token punctuation">(</span><span class="token string">"username"</span><span class="token punctuation">,</span> <span class="token string">"password"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><blockquote>
<p>The <code v-pre>only</code> method returns all of the key / value pairs that you request; however, it will not return key / value pairs that are not present on the request.</p>
</blockquote>
<h3 id="determining-if-an-input-value-is-present" tabindex="-1"><a class="header-anchor" href="#determining-if-an-input-value-is-present" aria-hidden="true">#</a> Determining If An Input Value Is Present</h3>
<p>You should use the <code v-pre>Has</code> method to determine if a value is present on the request. The <code v-pre>Has</code> method returns <code v-pre>true</code> if
the value is present on the request:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>user <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"data.user"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Map</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">if</span> user<span class="token punctuation">.</span><span class="token function">Has</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">//</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>When given multiple strings, the <code v-pre>Has</code> method will determine if all of the specified values are present:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>user <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"data.user"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Map</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">if</span> user<span class="token punctuation">.</span><span class="token function">Has</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">,</span> <span class="token string">"email"</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">//</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>The <code v-pre>HasAny</code> method returns <code v-pre>true</code> if any of the specified values are present:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>user <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"data.user"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Map</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">if</span> user<span class="token punctuation">.</span><span class="token function">HasAny</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">,</span> <span class="token string">"email"</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">//</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>To determine if a given key is absent from the request, you may use the <code v-pre>Missing</code> method:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>user <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"data.user"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Map</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">if</span> user<span class="token punctuation">.</span><span class="token function">Missing</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">//</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>If you would like to determine if a value is present on the request and is not empty, you may use the <code v-pre>Filled</code> method:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>user <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"data.user"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Map</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">if</span> user<span class="token punctuation">.</span><span class="token function">Filled</span><span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">//</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><blockquote>
<p>If you have a slice with multiple keys, you can use the spread operator: <code v-pre>.Has(keys...)</code></p>
</blockquote>
<h3 id="retrieving-cookies-from-requests" tabindex="-1"><a class="header-anchor" href="#retrieving-cookies-from-requests" aria-hidden="true">#</a> Retrieving Cookies From Requests</h3>
<p>To retrieve a cookie value from the request, use the <code v-pre>Cookie</code> method on a <code v-pre>inter.Request</code> instance:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>latestPage <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Cookie</span><span class="token punctuation">(</span><span class="token string">"latest_page"</span><span class="token punctuation">)</span>
latestPage<span class="token punctuation">,</span> err <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">CookieE</span><span class="token punctuation">(</span><span class="token string">"latest_page"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>If you are looking for how to set a cookie, you can read <RouterLink to="/the-basics/responses.html#attaching-cookies-to-responses">Attaching Cookies To Responses</RouterLink></p>
<blockquote>
<p>If you want to receive all original cookies, you can get the cookies from source by <code v-pre>request.Source().Cookies()</code></p>
</blockquote>
<h2 id="files" tabindex="-1"><a class="header-anchor" href="#files" aria-hidden="true">#</a> Files</h2>
<h3 id="retrieving-uploaded-files" tabindex="-1"><a class="header-anchor" href="#retrieving-uploaded-files" aria-hidden="true">#</a> Retrieving Uploaded Files</h3>
<p>You may access uploaded files from a <code v-pre>inter.Request</code> instance using the <code v-pre>File</code> method. The <code v-pre>File</code> method returns an
instance of the <code v-pre>support.File</code>, which holds the Go <code v-pre>multipart.File</code> interface (via <code v-pre>file.Source()</code>) and provides a variety of methods for
interacting with the file:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>file <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">File</span><span class="token punctuation">(</span><span class="token string">"photo"</span><span class="token punctuation">)</span>
file<span class="token punctuation">,</span> err <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">FileE</span><span class="token punctuation">(</span><span class="token string">"photo"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>Or you can use the <code v-pre>Files</code> method to retrieve multiple files:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>files <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Files</span><span class="token punctuation">(</span><span class="token string">"photos"</span><span class="token punctuation">)</span>
files<span class="token punctuation">,</span> err <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">FilesE</span><span class="token punctuation">(</span><span class="token string">"photos"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>You may determine if a file is present on the request:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">if</span> file<span class="token punctuation">,</span> err <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">FileE</span><span class="token punctuation">(</span><span class="token string">"photo"</span><span class="token punctuation">)</span><span class="token punctuation">;</span> err <span class="token operator">==</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span>
    <span class="token comment">//</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h3 id="file-paths-extensions" tabindex="-1"><a class="header-anchor" href="#file-paths-extensions" aria-hidden="true">#</a> File Paths &amp; Extensions</h3>
<p>The <code v-pre>support.File</code> struct also contains methods for accessing the file's fully-qualified path and its extension.
The <code v-pre>Extension</code> method will attempt to guess the file's extension based on its contents. This extension may be different
from the extension that was supplied by the client:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>name <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">File</span><span class="token punctuation">(</span><span class="token string">"photo"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token comment">// photo.jpg</span>

extension <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">File</span><span class="token punctuation">(</span><span class="token string">"photo"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Extension</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token comment">// .jpg</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div></template>
