<template><h1 id="responses" tabindex="-1"><a class="header-anchor" href="#responses" aria-hidden="true">#</a> Responses</h1>
<h2 id="creating-responses" tabindex="-1"><a class="header-anchor" href="#creating-responses" aria-hidden="true">#</a> Creating Responses</h2>
<h3 id="strings-slices" tabindex="-1"><a class="header-anchor" href="#strings-slices" aria-hidden="true">#</a> Strings &amp; Slices</h3>
<p>All routes and controllers should return a response to be sent back to the user's browser. Confetti provides several
different ways to return responses. The most basic response is returning a string from a route or controller with
function <code v-pre>outcome.Html</code>. The framework will automatically convert the string into a full HTTP response:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span><span class="token boolean">_</span> inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
    <span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Html</span><span class="token punctuation">(</span><span class="token string">"Hello World"</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>In addition to returning strings from your routes and controllers, you may also return slices with
function <code v-pre>outcome.Json</code>. The framework will automatically convert the slice into a JSON response:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span><span class="token boolean">_</span> inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
    <span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Json</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">int</span><span class="token punctuation">{</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">2</span><span class="token punctuation">,</span><span class="token number">3</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><blockquote>
<p>Did you know you can also return <code v-pre>support.Collection</code> and <code v-pre>support.Map</code> from your routes or controllers? They will automatically be converted to JSON. Give it a shot!</p>
</blockquote>
<h3 id="response-objects" tabindex="-1"><a class="header-anchor" href="#response-objects" aria-hidden="true">#</a> Response Objects</h3>
<p>Functions <code v-pre>outcome.Html</code>, <code v-pre>outcome.Json</code> and <code v-pre>outcome.Content</code> return an object with interface <code v-pre>inter.Response</code>. That
allows you to customize the response's HTTP status code and headers:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"home"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span><span class="token boolean">_</span> inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
    <span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Html</span><span class="token punctuation">(</span><span class="token string">"Hello World"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
        <span class="token function">Status</span><span class="token punctuation">(</span><span class="token number">200</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
        <span class="token function">Header</span><span class="token punctuation">(</span><span class="token string">"Content-Type"</span><span class="token punctuation">,</span> <span class="token string">"text/plain"</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="highlight-lines"><br><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><br></div><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p><code v-pre>outcome.Html</code> and <code v-pre>outcome.Json</code> will add a Content-Type header. Use <code v-pre>outcome.Content</code> to add <code v-pre>Content-Type</code> header
yourself.</p>
<h3 id="attaching-headers-to-responses" tabindex="-1"><a class="header-anchor" href="#attaching-headers-to-responses" aria-hidden="true">#</a> Attaching Headers To Responses</h3>
<p>Keep in mind that most response methods are chainable, allowing for the fluent construction of response instances. For
example, you may use the <code v-pre>Header</code> method to add a series of headers to the response before sending it back to the user:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"# Cool Stuff"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
    <span class="token function">Header</span><span class="token punctuation">(</span><span class="token string">"Content-Type"</span><span class="token punctuation">,</span> <span class="token string">"text/markdown"</span><span class="token punctuation">,</span> <span class="token string">"charset=UTF-8"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
    <span class="token function">Header</span><span class="token punctuation">(</span><span class="token string">"X-Header-One"</span><span class="token punctuation">,</span> <span class="token string">"Header Value"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>Or, you may use the <code v-pre>Headers</code> method to specify a slice of headers to be added to the response:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"# Cool Stuff"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
    <span class="token function">Headers</span><span class="token punctuation">(</span>http<span class="token punctuation">.</span>Header<span class="token punctuation">{</span>
        <span class="token string">"Content-Type"</span><span class="token punctuation">:</span> <span class="token punctuation">{</span><span class="token string">"application/markdown"</span><span class="token punctuation">,</span> <span class="token string">"charset=UTF-8"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
        <span class="token string">"X-Header-One"</span><span class="token punctuation">:</span> <span class="token punctuation">{</span><span class="token string">"Header Value"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h3 id="attaching-cookies-to-responses" tabindex="-1"><a class="header-anchor" href="#attaching-cookies-to-responses" aria-hidden="true">#</a> Attaching Cookies To Responses</h3>
<p>The <code v-pre>Cookie</code> method on response instances allows you to easily attach cookies to the response. For example, you may use
the <code v-pre>Cookie</code> method to generate a cookie and fluently attach it to the response instance like so:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Html</span><span class="token punctuation">(</span><span class="token string">"Hello World"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
    <span class="token function">Cookie</span><span class="token punctuation">(</span>http<span class="token punctuation">.</span>Cookie<span class="token punctuation">{</span>Name<span class="token punctuation">:</span> <span class="token string">"request_id"</span><span class="token punctuation">,</span> Value<span class="token punctuation">:</span> <span class="token string">"aGdsf89hA3jr2"</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="redirects" tabindex="-1"><a class="header-anchor" href="#redirects" aria-hidden="true">#</a> Redirects</h2>
<p>Redirect responses are instances of the <code v-pre>outcome.redirectResponse</code> struct, and contain the proper headers needed to
redirect the user to another URL. There are several ways to generate a <code v-pre>outcome.redirectResponse</code> instance. The simplest
method is to use the <code v-pre>outcome.RedirectPermanent</code> or the <code v-pre>outcome.RedirectTemporary</code> function:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>    <span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"dashboard"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span><span class="token boolean">_</span> inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
        <span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">RedirectPermanent</span><span class="token punctuation">(</span><span class="token string">"home/dashboard"</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>    <span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"login"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span><span class="token boolean">_</span> inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
        <span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">RedirectTemporary</span><span class="token punctuation">(</span><span class="token string">"under_construction"</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>Or you can use <code v-pre>outcome.Redirect</code> to determine the HTTP status yourself.</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>outcome<span class="token punctuation">.</span><span class="token function">Redirect</span><span class="token punctuation">(</span><span class="token string">"home/dashboard"</span><span class="token punctuation">,</span> net<span class="token punctuation">.</span>StatusPermanentRedirect<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="redirecting-to-external-domains" tabindex="-1"><a class="header-anchor" href="#redirecting-to-external-domains" aria-hidden="true">#</a> Redirecting To External Domains</h3>
<p>Sometimes you may need to redirect to a domain outside of your application. Even then you can use the above methods:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">RedirectTemporary</span><span class="token punctuation">(</span><span class="token string">"https://github.com/confetti-framework"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="redirecting-to-named-routes" tabindex="-1"><a class="header-anchor" href="#redirecting-to-named-routes" aria-hidden="true">#</a> Redirecting To Named Routes</h3>
<p>When you call the <code v-pre>outcome.RedirectToRoute</code> function with the route name, the user will be redirected to that route.</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">RedirectToRoute</span><span class="token punctuation">(</span>request<span class="token punctuation">.</span><span class="token function">App</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">"login"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>If your route has parameters, you may pass them as an extra argument to the method:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token comment">// For a route with the following URI: profile/{id}</span>

<span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">RedirectToRoute</span><span class="token punctuation">(</span>request<span class="token punctuation">.</span><span class="token function">App</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">"profile"</span><span class="token punctuation">,</span> outcome<span class="token punctuation">.</span>Parameters<span class="token punctuation">{</span><span class="token string">"id"</span><span class="token punctuation">:</span> <span class="token number">12</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h3 id="redirecting-to-controller-actions" tabindex="-1"><a class="header-anchor" href="#redirecting-to-controller-actions" aria-hidden="true">#</a> Redirecting To Controller Actions</h3>
<p>You may also redirect the request to controller actions. To do so, simply call the controller:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">return</span> controllers<span class="token punctuation">.</span><span class="token function">Homepage</span><span class="token punctuation">(</span>request<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="other-response-types" tabindex="-1"><a class="header-anchor" href="#other-response-types" aria-hidden="true">#</a> Other Response Types</h2>
<p>The <code v-pre>outcome</code> package may be used to generate other types of response instances. The <code v-pre>outcome</code> package provides several
helpful function for generating responses.</p>
<h3 id="json-responses" tabindex="-1"><a class="header-anchor" href="#json-responses" aria-hidden="true">#</a> JSON Responses</h3>
<p>The <code v-pre>outcome.Json</code> method will automatically set the <code v-pre>Content-Type</code> header to <code v-pre>application/json</code>, as well as convert the
given object to JSON using <code v-pre>json.Marshal</code>:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Json</span><span class="token punctuation">(</span><span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">{</span>
    <span class="token string">"name"</span><span class="token punctuation">:</span> <span class="token string">"abigail"</span><span class="token punctuation">,</span>
    <span class="token string">"state"</span><span class="token punctuation">:</span> <span class="token string">"CA"</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="view-responses" tabindex="-1"><a class="header-anchor" href="#view-responses" aria-hidden="true">#</a> View Responses</h3>
<p>If you need control over the response's status and headers but also need to return a <a href="views">view</a> as
the response's content, you can use the <code v-pre>outcome.Html</code> method with a created view:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Html</span><span class="token punctuation">(</span>views<span class="token punctuation">.</span><span class="token function">Homepage</span><span class="token punctuation">(</span><span class="token string">"James"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Status</span><span class="token punctuation">(</span><span class="token number">200</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="file-downloads" tabindex="-1"><a class="header-anchor" href="#file-downloads" aria-hidden="true">#</a> File Downloads</h3>
<p>Function <code v-pre>Download</code> may be used to generate a response that forces the user's browser to download the file at the given
path. The response of the <code v-pre>Download</code> method accepts the method <code v-pre>Filename</code>, which will determine the file name that is
seen by the user downloading the file. <code v-pre>Content-Type</code> with MIME type is automatically filled in based on the file
extension.</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Download</span><span class="token punctuation">(</span>filePath<span class="token punctuation">)</span>

<span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Download</span><span class="token punctuation">(</span>filePath<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Filename</span><span class="token punctuation">(</span><span class="token string">"label.pdf"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>The file may not be found. Instead of a panic, <code v-pre>DownloadE</code> allows you to choose to handle your errors with more love.</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>response<span class="token punctuation">,</span> err <span class="token operator">:=</span> outcome<span class="token punctuation">.</span><span class="token function">DownloadE</span><span class="token punctuation">(</span>filePath<span class="token punctuation">)</span>
<span class="token keyword">if</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> err<span class="token punctuation">.</span><span class="token function">Level</span><span class="token punctuation">(</span>log_level<span class="token punctuation">.</span>NOTICE<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><blockquote>
<p>The file being downloaded need to have an ASCII file name.</p>
</blockquote>
<h3 id="streamed-downloads" tabindex="-1"><a class="header-anchor" href="#streamed-downloads" aria-hidden="true">#</a> Streamed Downloads</h3>
<p>Sometimes you may wish to turn the string response of a given operation into a downloadable response without having to
write the contents of the operation to disk. You may use the <code v-pre>Content</code> function in this scenario:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"%PDF-1.5"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
    <span class="token function">Header</span><span class="token punctuation">(</span><span class="token string">"Content-Type"</span><span class="token punctuation">,</span> <span class="token string">"application/pdf"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
    <span class="token function">FileName</span><span class="token punctuation">(</span><span class="token string">"labels.pdf"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h3 id="show-in-browser" tabindex="-1"><a class="header-anchor" href="#show-in-browser" aria-hidden="true">#</a> Show In Browser</h3>
<p>Function <code v-pre>ShowInBrowser</code> may be used to display a file, such as an image or PDF, directly in the user's browser instead
of initiating a download:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Content</span><span class="token punctuation">(</span><span class="token string">"%PDF-1.5"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
    <span class="token function">Header</span><span class="token punctuation">(</span><span class="token string">"Content-Type"</span><span class="token punctuation">,</span> <span class="token string">"application/pdf"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>
    <span class="token function">ShowInBrowser</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div></template>
