<template><div><h1 id="routing" tabindex="-1"><a class="header-anchor" href="#routing" aria-hidden="true">#</a> Routing</h1>
<h2 id="basic-routing" tabindex="-1"><a class="header-anchor" href="#basic-routing" aria-hidden="true">#</a> Basic Routing</h2>
<p>The most basic Confetti routes accept a URI and a <code v-pre>Closure</code>, providing a very simple and expressive method of defining routes:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
    <span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Html</span><span class="token punctuation">(</span><span class="token string">"Hello World"</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>If you are using multiple routers, it is recommended to place a reference to a function in the second parameter:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>User<span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="the-default-route-files" tabindex="-1"><a class="header-anchor" href="#the-default-route-files" aria-hidden="true">#</a> The Default Route Files</h3>
<p>All Confetti routes are defined in your route files, which are located in the <code v-pre>routes</code> directory. These files are
automatically loaded by the framework. The <code v-pre>routes/web.go</code> file defines routes that are for your web interface. These
routes are assigned the <code v-pre>Web</code> middleware group. The routes in <code v-pre>routes/api.go</code> are stateless and are assigned the <code v-pre>Api</code>
middleware group.</p>
<p>The routes defined in <code v-pre>routes/web.go</code> may be accessed by entering the defined route's URL in your browser. For example,
you may access the following route by navigating to <code v-pre>http://localhost/user</code> in your browser:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>User<span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Routes defined in the <code v-pre>routes/api.go</code> file are nested within a route group. Within this group, the <code v-pre>/api</code> URI prefix is automatically applied, so you do not need to manually apply it to every route in the file. You may modify the prefix and other route group options by using multiple methods.</p>
<h3 id="available-router-methods" tabindex="-1"><a class="header-anchor" href="#available-router-methods" aria-hidden="true">#</a> Available Router Methods</h3>
<p>The router allows you to register routes that respond to any HTTP verb:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/photos"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>PhotosIndex<span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token function">Post</span><span class="token punctuation">(</span><span class="token string">"/photos"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>PhotosStore<span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token function">Put</span><span class="token punctuation">(</span><span class="token string">"/photos/{photo}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>PhotosUpdate<span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token function">Patch</span><span class="token punctuation">(</span><span class="token string">"/photos/{photo}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>PhotosUpdate<span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token function">Delete</span><span class="token punctuation">(</span><span class="token string">"/photos/{photo}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>PhotosDestroy<span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Sometimes you may need to register a route that responds to multiple HTTP verbs. You may do so using the <code v-pre>Match</code> method:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Match</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">{</span>method<span class="token punctuation">.</span>Get<span class="token punctuation">,</span> method<span class="token punctuation">.</span>Post<span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token string">"/photos/{photo}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>Photos<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Or, you may even register a route that responds to all HTTP verbs using the <code v-pre>Any</code> method:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Any</span><span class="token punctuation">(</span><span class="token string">"/photos/{photo}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>Photos<span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="redirect-routes" tabindex="-1"><a class="header-anchor" href="#redirect-routes" aria-hidden="true">#</a> Redirect Routes</h3>
<p>If you are defining a route that redirects to another URI, you may use <code v-pre>Redirect</code>. This function provides a convenient shortcut so that you do not have to define a full route or controller for performing a simple redirect:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Redirect</span><span class="token punctuation">(</span><span class="token string">"/here"</span><span class="token punctuation">,</span> <span class="token string">"/there"</span><span class="token punctuation">,</span> <span class="token number">302</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>You may use the <code v-pre>RedirectTemporary</code> method to return a <code v-pre>302</code> status code:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">RedirectTemporary</span><span class="token punctuation">(</span><span class="token string">"/here"</span><span class="token punctuation">,</span> <span class="token string">"/there"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Or the <code v-pre>RedirectPermanent</code> method to return a <code v-pre>301</code> status code:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">RedirectPermanent</span><span class="token punctuation">(</span><span class="token string">"/here"</span><span class="token punctuation">,</span> <span class="token string">"/there"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="view-routes" tabindex="-1"><a class="header-anchor" href="#view-routes" aria-hidden="true">#</a> View Routes</h3>
<p>If your route only needs to return a view, you may use the <code v-pre>View</code> method. Like the <code v-pre>Redirect</code> method, this method
provides a simple shortcut so that you do not have to define a full route or controller. The <code v-pre>View</code> method accepts a URI
as its first argument, and a view name as its second argument:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">View</span><span class="token punctuation">(</span><span class="token char">'/profile'</span><span class="token punctuation">,</span> views<span class="token punctuation">.</span><span class="token function">Profile</span><span class="token punctuation">(</span><span class="token string">"James"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="route-parameters" tabindex="-1"><a class="header-anchor" href="#route-parameters" aria-hidden="true">#</a> Route Parameters</h2>
<h3 id="required-parameters" tabindex="-1"><a class="header-anchor" href="#required-parameters" aria-hidden="true">#</a> Required Parameters</h3>
<p>Sometimes you will need to capture segments of the URI within your route. For example, you may need to capture a username from the URL. You may do so by defining route parameters:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user/{username}"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
    name <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"username"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Html</span><span class="token punctuation">(</span><span class="token string">"User "</span> <span class="token operator">+</span> name<span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>You may define as many route parameters as required by your route:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"posts/{post_id}/comments/{comment_alias}"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
    postId <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"post_id"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Int</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    commentAlias <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"comment_alias"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token comment">//</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>If the parameter cannot be found, then it will panic with an error. Do you want more control over the errors? Then use methods with the suffix E to receive the error:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>postId<span class="token punctuation">,</span> err <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">ParameterE</span><span class="token punctuation">(</span><span class="token string">"post_id"</span><span class="token punctuation">)</span>
<span class="token keyword">if</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span>
    <span class="token comment">// postId.Int()</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>Route parameters are always encased within <code v-pre>{}</code> braces and should consist of alphabetic characters, and may not contain a <code v-pre>-</code> character. Instead of using the <code v-pre>-</code> character, use an underscore (<code v-pre>_</code>).</p>
</blockquote>
<h3 id="optional-parameters" tabindex="-1"><a class="header-anchor" href="#optional-parameters" aria-hidden="true">#</a> Optional Parameters</h3>
<p>Occasionally you may need to specify a route parameter, but make the presence of that route parameter optional. You may do so by placing a <code v-pre>?</code> mark after the parameter name. If no value is found, an empty string or a zero is given.</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"users/{username?}/comment/{comment_id?}"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
    userName <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"username"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token comment">// userName = ""</span>

    commentId <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"comment_id"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Int</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token comment">// commentId = 0</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="highlight-lines"><div class="highlight-line">&nbsp;</div><br><br><br><br><br><br></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Use Empty or Present to check if a value is present.</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>userName <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"username"</span><span class="token punctuation">)</span>
<span class="token keyword">if</span> userName<span class="token punctuation">.</span><span class="token function">Empty</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// userName is empty</span>
<span class="token punctuation">}</span>

commentId <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"comment_id"</span><span class="token punctuation">)</span>
<span class="token keyword">if</span> commentId<span class="token punctuation">.</span><span class="token function">Filled</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// commentId.Int()</span>
<span class="token punctuation">}</span>
</code></pre><div class="highlight-lines"><br><div class="highlight-line">&nbsp;</div><br><br><br><br><div class="highlight-line">&nbsp;</div><br><br></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="regular-expression-constraints" tabindex="-1"><a class="header-anchor" href="#regular-expression-constraints" aria-hidden="true">#</a> Regular Expression Constraints</h3>
<p>You may constrain the format of your route parameters using regex. The key and regular expression must be separated by a colon:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user/{username:[a-z_]+}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserShow<span class="token punctuation">)</span>
<span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user/{id:[0-9]+}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserShow<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Or define a restriction separately:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user/{id}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserShow<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"id"</span><span class="token punctuation">,</span> <span class="token string">"[0-9]+"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h4 id="global-constraints" tabindex="-1"><a class="header-anchor" href="#global-constraints" aria-hidden="true">#</a> Global Constraints</h4>
<p>If you would like a route parameter to always be constrained by a given regular expression, you may use the <code v-pre>WhereMulti</code> method. You should define these patterns in the <code v-pre>Boot</code> method of your <code v-pre>RouteServiceProvider</code> after the collection is filled:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">func</span> <span class="token punctuation">(</span>p RouteServiceProvider<span class="token punctuation">)</span> <span class="token function">Boot</span><span class="token punctuation">(</span>container inter<span class="token punctuation">.</span>Container<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Container <span class="token punctuation">{</span>
    collection <span class="token operator">:=</span> routing<span class="token punctuation">.</span><span class="token function">NewRouteCollection</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    collection<span class="token punctuation">.</span><span class="token function">Merge</span><span class="token punctuation">(</span>routes<span class="token punctuation">.</span>Api<span class="token punctuation">)</span>
    collection<span class="token punctuation">.</span><span class="token function">Merge</span><span class="token punctuation">(</span>routes<span class="token punctuation">.</span>Web<span class="token punctuation">)</span>

    collection<span class="token punctuation">.</span><span class="token function">WhereMulti</span><span class="token punctuation">(</span><span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">{</span>
        <span class="token string">"id"</span><span class="token punctuation">:</span> <span class="token string">"[0-9]+"</span><span class="token punctuation">,</span>
        <span class="token string">"username"</span><span class="token punctuation">:</span> <span class="token string">"[a-z_]+"</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span>

    <span class="token comment">//</span>
<span class="token punctuation">}</span>
</code></pre><div class="highlight-lines"><br><br><br><br><br><br><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><br><br><br></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Once the pattern has been defined, it is automatically applied to all routes using that parameter name:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token comment">// Only executed if {id} is numeric...</span>
<span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user/{id}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserShow<span class="token punctuation">)</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="encoded-forward-slashes" tabindex="-1"><a class="header-anchor" href="#encoded-forward-slashes" aria-hidden="true">#</a> Encoded Forward Slashes</h4>
<p>The Confetti routing component allows all characters except <code v-pre>/</code>. You must explicitly allow <code v-pre>/</code> to be part of your placeholder using a <code v-pre>Where</code> condition regular expression:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/search/{search}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserIndex<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Where</span><span class="token punctuation">(</span><span class="token string">"search"</span><span class="token punctuation">,</span> <span class="token string">".*"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><blockquote>
<p>Encoded forward slashes are only supported within the last route segment.</p>
</blockquote>
<h3 id="route-model-binding" tabindex="-1"><a class="header-anchor" href="#route-model-binding" aria-hidden="true">#</a> Route Model Binding</h3>
<p>For simple transformation of a parameter to a model, you can bind a model to a parameter. You can use the RouteModelBinding middleware for this:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">func</span> <span class="token punctuation">(</span>r RouteModelBinding<span class="token punctuation">)</span> <span class="token function">Handle</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">,</span> next inter<span class="token punctuation">.</span>Next<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
	request<span class="token punctuation">.</span><span class="token function">App</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Singleton</span><span class="token punctuation">(</span><span class="token string">"user"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span><span class="token punctuation">)</span> model<span class="token punctuation">.</span>User <span class="token punctuation">{</span>
		userId <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"user_id"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Int</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
		<span class="token keyword">return</span> model<span class="token punctuation">.</span><span class="token function">FindUser</span><span class="token punctuation">(</span>userId<span class="token punctuation">)</span>
	<span class="token punctuation">}</span><span class="token punctuation">)</span>

    <span class="token keyword">return</span> <span class="token function">next</span><span class="token punctuation">(</span>request<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="highlight-lines"><br><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><br><br><br></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Later you can retrieve the user from the container:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>user <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Make</span><span class="token punctuation">(</span><span class="token string">"user"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token punctuation">(</span>model<span class="token punctuation">.</span>User<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><blockquote>
<p>The callback ensures that the user is only received from the database when you need it (one time in each request). This can be nice if you first want to validate the request before accessing the database.</p>
</blockquote>
<h2 id="named-routes" tabindex="-1"><a class="header-anchor" href="#named-routes" aria-hidden="true">#</a> Named Routes</h2>
<p>Named routes allow the convenient generation of URLs or redirects for specific routes. You may specify a name for a route by chaining the <code v-pre>Name</code> method onto the route definition:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user/roles"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserRoleIndex<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token string">"user.roles"</span><span class="token punctuation">)</span>
<span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user/comments"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserCommentIndex<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token string">"user.comments"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Or you can name a group:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Group</span><span class="token punctuation">(</span>
    <span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/roles"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserRoleIndex<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token string">"roles"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/comments"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserCommentIndex<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token string">"comments"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Prefix</span><span class="token punctuation">(</span><span class="token string">"/user"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token string">"user."</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>The names of the above routes are <code v-pre>user.roles</code> and <code v-pre>user.comments</code>.</p>
<h3 id="generating-urls-to-named-routes" tabindex="-1"><a class="header-anchor" href="#generating-urls-to-named-routes" aria-hidden="true">#</a> Generating URLs To Named Routes</h3>
<p>Once you have assigned a name to a given route, you may use the route's name when redirects via the <code v-pre>RedirectToRoute</code> function:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token comment">// Generating Redirects...</span>
<span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/comments"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
    <span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">RedirectToRoute</span><span class="token punctuation">(</span>request<span class="token punctuation">.</span><span class="token function">App</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">"user.roles"</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Or you use the route's name when generating URLs via the
<code v-pre>UrlByName</code> function:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token comment">// Generating URLs...</span>
url <span class="token operator">:=</span> routing<span class="token punctuation">.</span><span class="token function">UrlByName</span><span class="token punctuation">(</span>app<span class="token punctuation">,</span> <span class="token string">"user.roles"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>If the named route defines parameters, you may pass the parameters as the third argument to the <code v-pre>UrlByName</code> function. The given parameters will automatically be inserted into the URL in their correct positions:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user/{id}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserShow<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token string">"user"</span><span class="token punctuation">)</span>

url <span class="token operator">:=</span> outcome<span class="token punctuation">.</span><span class="token function">UrlByName</span><span class="token punctuation">(</span>request<span class="token punctuation">.</span><span class="token function">App</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">"user"</span><span class="token punctuation">,</span> outcome<span class="token punctuation">.</span>Parameters<span class="token punctuation">{</span><span class="token string">"id"</span><span class="token punctuation">:</span> <span class="token number">12</span><span class="token punctuation">}</span><span class="token punctuation">)</span>

<span class="token operator">/</span>user<span class="token operator">/</span><span class="token number">12</span>
</code></pre><div class="highlight-lines"><br><br><div class="highlight-line">&nbsp;</div><br><br></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>If you also want to build a query string, use the 4th parameter, those key / value pairs will automatically be added to the generated URL's query string:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user/{id}"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserShow<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token string">"user"</span><span class="token punctuation">)</span>

routing<span class="token punctuation">.</span><span class="token function">UrlByName</span><span class="token punctuation">(</span>
    app<span class="token punctuation">,</span>
    <span class="token string">"user"</span><span class="token punctuation">,</span>
    routing<span class="token punctuation">.</span>Parameters<span class="token punctuation">{</span><span class="token string">"id"</span><span class="token punctuation">:</span> <span class="token number">12</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    routing<span class="token punctuation">.</span>Parameters<span class="token punctuation">{</span><span class="token string">"order_by"</span><span class="token punctuation">:</span> <span class="token string">"name"</span><span class="token punctuation">,</span> <span class="token string">"size"</span><span class="token punctuation">:</span> <span class="token number">50</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">)</span>

<span class="token operator">/</span>user<span class="token operator">/</span><span class="token number">12</span>?order_by<span class="token operator">=</span>name<span class="token operator">&amp;</span>size<span class="token operator">=</span><span class="token number">50</span>
</code></pre><div class="highlight-lines"><br><br><br><br><br><br><div class="highlight-line">&nbsp;</div><br><br><br></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="inspecting-the-current-route" tabindex="-1"><a class="header-anchor" href="#inspecting-the-current-route" aria-hidden="true">#</a> Inspecting The Current Route</h3>
<p>If you would like to determine if the current route name contains a given string. You may use the <code v-pre>Named</code> method on a Route instance. For example, you may check the current route name from a route middleware:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">func</span> <span class="token punctuation">(</span>v ValidatePostSize<span class="token punctuation">)</span> <span class="token function">Handle</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">,</span> next inter<span class="token punctuation">.</span>Next<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
    <span class="token keyword">if</span> request<span class="token punctuation">.</span><span class="token function">Route</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Named</span><span class="token punctuation">(</span><span class="token string">"profile"</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">//</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">return</span> <span class="token function">next</span><span class="token punctuation">(</span>request<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="highlight-lines"><br><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><br><br><br></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="route-groups" tabindex="-1"><a class="header-anchor" href="#route-groups" aria-hidden="true">#</a> Route Groups</h2>
<p>Route groups allow you to share route attributes, such as middleware or prefixes, across many routes without needing to define those attributes on each individual route. Shared attributes are specified after the <code v-pre>Group</code> method.</p>
<p>Nested groups attempt to intelligently &quot;merge&quot; attributes with their parent group.</p>
<h3 id="middleware" tabindex="-1"><a class="header-anchor" href="#middleware" aria-hidden="true">#</a> Middleware</h3>
<p>To assign middleware to all routes within a group, you may use the <code v-pre>Middleware</code> method after defining the group. Middlewares are executed in the order they are listed:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Group</span><span class="token punctuation">(</span>
    <span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/roles"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>RoleIndex<span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/comments"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>CommentIndex<span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Middleware</span><span class="token punctuation">(</span>First<span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span> Second<span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="subdomain-routing" tabindex="-1"><a class="header-anchor" href="#subdomain-routing" aria-hidden="true">#</a> Subdomain Routing</h3>
<p>Route groups may also be used to handle subdomain routing. The subdomain may be specified by calling the <code v-pre>Domain</code> method after defining the group:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Group</span><span class="token punctuation">(</span>
    <span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/users"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserIndex<span class="token punctuation">,</span>
<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Domain</span><span class="token punctuation">(</span><span class="token string">"api.myapp.com"</span><span class="token punctuation">)</span>
</code></pre><div class="highlight-lines"><br><br><br></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Subdomains may be assigned route parameters just like route URIs, allowing you to capture a portion of the subdomain for usage in your controller:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Group</span><span class="token punctuation">(</span>
    <span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/user/{id}"</span><span class="token punctuation">,</span> <span class="token keyword">func</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
        account <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"account"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        userId <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Parameter</span><span class="token punctuation">(</span><span class="token string">"id"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Int</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token comment">//</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Domain</span><span class="token punctuation">(</span><span class="token string">"{account}.myapp.com"</span><span class="token punctuation">)</span>
</code></pre><div class="highlight-lines"><br><br><br><br><br><br><div class="highlight-line">&nbsp;</div></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>In order to ensure your subdomain routes are reachable, you should register subdomain routes before registering root domain routes. This will prevent root domain routes from overwriting subdomain routes which have the same URI path.</p>
</blockquote>
<h3 id="route-prefixes" tabindex="-1"><a class="header-anchor" href="#route-prefixes" aria-hidden="true">#</a> Route Prefixes</h3>
<p>The <code v-pre>Prefix</code> method may be used to prefix each route in the group with a given URI. For example, you may want to prefix all route URIs within the group with <code v-pre>admin</code>:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Group</span><span class="token punctuation">(</span>
    <span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/users"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserShow<span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Prefix</span><span class="token punctuation">(</span><span class="token string">"/admin"</span><span class="token punctuation">)</span>

<span class="token comment">// Matches "/admin/users"</span>
</code></pre><div class="highlight-lines"><br><br><div class="highlight-line">&nbsp;</div><br><br></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="route-name-prefixes" tabindex="-1"><a class="header-anchor" href="#route-name-prefixes" aria-hidden="true">#</a> Route Name Prefixes</h3>
<p>The <code v-pre>Name</code> method may be used to prefix each route name in the group with a given string. For example, you may want to prefix all the grouped route's names with <code v-pre>admin</code>. The given string is prefixed to the route name exactly as it is specified, so we will be sure to provide the trailing <code v-pre>.</code> character in the prefix:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Group</span><span class="token punctuation">(</span>
    <span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/users"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserShow<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token string">"users"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token string">"admin."</span><span class="token punctuation">)</span>

<span class="token comment">// Matches "admin.users"</span>
</code></pre><div class="highlight-lines"><br><br><div class="highlight-line">&nbsp;</div><br><br></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="fallback-routes" tabindex="-1"><a class="header-anchor" href="#fallback-routes" aria-hidden="true">#</a> Fallback Routes</h2>
<p>Typically, unhandled requests will automatically render a &quot;404&quot; page via your application's exception handler. Using
the <code v-pre>Fallback</code> function, you may define a route that will be executed when no other route matches the incoming request.</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token function">Group</span><span class="token punctuation">(</span>
    <span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"/users"</span><span class="token punctuation">,</span> controllers<span class="token punctuation">.</span>UserShow<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token string">"users"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token function">Fallback</span><span class="token punctuation">(</span><span class="token keyword">func</span><span class="token punctuation">(</span>request inter<span class="token punctuation">.</span>Request<span class="token punctuation">)</span> inter<span class="token punctuation">.</span>Response <span class="token punctuation">{</span>
        <span class="token keyword">return</span> outcome<span class="token punctuation">.</span><span class="token function">Html</span><span class="token punctuation">(</span><span class="token string">"404 Page not found"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Status</span><span class="token punctuation">(</span><span class="token number">404</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">)</span>
</code></pre><div class="highlight-lines"><br><br><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><br></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>The fallback route should always be the last route registered in a group.</p>
</blockquote>
<h2 id="accessing-the-current-route" tabindex="-1"><a class="header-anchor" href="#accessing-the-current-route" aria-hidden="true">#</a> Accessing The Current Route</h2>
<p>You can get the current router from the container:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>app<span class="token punctuation">.</span><span class="token function">Make</span><span class="token punctuation">(</span><span class="token string">"route"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token punctuation">(</span>inter<span class="token punctuation">.</span>Route<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Or get the route from the request:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>request<span class="token punctuation">.</span><span class="token function">Route</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>You may use the <code v-pre>Name</code>, <code v-pre>Method</code> and <code v-pre>Domain</code> methods on the <code v-pre>Route</code> to access information about the route handling the incoming request:</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code>name <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Route</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
method <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Route</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Method</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
domain <span class="token operator">:=</span> request<span class="token punctuation">.</span><span class="token function">Route</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Domain</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


